name: 'Python import time'
description: 'Bound the time it takes for some python code to import stuff'
inputs:
  code:
    description: 'The code to measure.'
    required: True
  threshold:
    description: 'The time threshold. If the code takes longer than that to import stuff, the action will fail.'
    required: False
    default: 250000

runs:
  using: "composite"
  steps:

    - name: Check import time of `${{inputs.code}}` ⏳
      shell: bash
      env:
        CODE: ${{inputs.code}}
        THRESHOLD: ${{inputs.threshold}}
      run: |
        bash ${{ github.action_path }}/importtime.sh "${CODE}" "${THRESHOLD}"
