name: 'Python import time'
description: 'Bound the time it takes for some python code to import stuff'
inputs:
  code:
    description: 'The code to measure.'
    required: True
  threshold:
    description: 'The time threshold. If the code takes longer than that to import stuff, the action will fail.'
    required: False
    default: 250000

runs:
  using: "composite"
  steps:

    - name: Check import time of `${{inputs.code}}` â³
      shell: bash
      run: |
        importtime="$(python -X importtime -c ${{inputs.code}} 2>&1 | tail -1 | sed 's/^.*| *\([0-9][0-9]*\) *|.*$/\1/g')"
        echo "Import time for '${{inputs.code}}' is ${importtime} and threshold is ${{inputs.threshold}}"
        test "$importtime" -le ${{inputs.threshold}}
